-- Basketball seasons: explicit season records and round assignment.

create table if not exists public.basketball_seasons (
  id bigint generated by default as identity primary key,
  season_number integer not null unique,
  display_name text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  is_active boolean not null default false,
  schema_version integer not null default 1,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (ends_at > starts_at)
);

create unique index if not exists basketball_seasons_one_active_idx
  on public.basketball_seasons ((is_active))
  where is_active = true;

create trigger set_basketball_seasons_updated_at
before update on public.basketball_seasons
for each row
execute function public.set_updated_at();

alter table public.rounds
  add column if not exists basketball_season_id bigint
  references public.basketball_seasons (id) on delete restrict;

create index if not exists rounds_basketball_season_id_idx
  on public.rounds (basketball_season_id)
  where game_type_id = 'basketball';

-- Season 1: all historical basketball data through 2026-06-20 America/Los_Angeles end-of-day.
-- Season 2+ boundaries follow solstice windows (managed by sync function).
insert into public.basketball_seasons (
  season_number,
  display_name,
  starts_at,
  ends_at,
  is_active,
  schema_version
)
values (
  1,
  'Season 1',
  timestamptz '1970-01-01 00:00:00+00',
  timestamptz '2026-06-21 07:00:00+00',
  true,
  1
);

update public.rounds
set basketball_season_id = 1
where game_type_id = 'basketball'
  and basketball_season_id is null;

alter table public.basketball_seasons enable row level security;

create policy "public_read_basketball_seasons"
on public.basketball_seasons
for select
to anon, authenticated
using (true);

-- Returns active season id; rolls forward when now >= active.ends_at.
create or replace function public.ensure_basketball_season_active()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  active_row public.basketball_seasons%rowtype;
  next_number integer;
  next_starts timestamptz;
  next_ends timestamptz;
  next_name text;
begin
  select *
  into active_row
  from public.basketball_seasons
  where is_active = true
  order by season_number desc
  limit 1
  for update;

  if not found then
    raise exception 'No active basketball season configured';
  end if;

  if now() < active_row.ends_at then
    return active_row.id;
  end if;

  update public.basketball_seasons
  set is_active = false,
      updated_at = timezone('utc', now())
  where id = active_row.id;

  next_number := active_row.season_number + 1;
  next_starts := active_row.ends_at;

  -- Summer: Jun 21 -> Dec 21; Winter: Dec 21 -> Jun 21 (half-open [starts, ends)).
  if extract(month from timezone('America/Los_Angeles', next_starts)) = 6 then
    next_ends := (
      make_timestamptz(
        extract(year from timezone('America/Los_Angeles', next_starts))::integer,
        12,
        21,
        0,
        0,
        0,
        'America/Los_Angeles'
      )
    );
  else
    next_ends := (
      make_timestamptz(
        extract(year from timezone('America/Los_Angeles', next_starts))::integer + 1,
        6,
        21,
        0,
        0,
        0,
        'America/Los_Angeles'
      )
    );
  end if;

  next_name := 'Season ' || next_number::text;

  insert into public.basketball_seasons (
    season_number,
    display_name,
    starts_at,
    ends_at,
    is_active,
    schema_version
  )
  values (
    next_number,
    next_name,
    next_starts,
    next_ends,
    true,
    active_row.schema_version
  )
  returning id into active_row.id;

  return active_row.id;
end;
$$;

grant execute on function public.ensure_basketball_season_active() to anon, authenticated;

-- Admin-only forced rollover (same as auto when past end; can run early).
create or replace function public.force_basketball_season_rollover()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  active_row public.basketball_seasons%rowtype;
  next_number integer;
  next_starts timestamptz;
  next_ends timestamptz;
begin
  select *
  into active_row
  from public.basketball_seasons
  where is_active = true
  order by season_number desc
  limit 1
  for update;

  if not found then
    raise exception 'No active basketball season configured';
  end if;

  update public.basketball_seasons
  set is_active = false,
      ends_at = least(ends_at, timezone('utc', now())),
      updated_at = timezone('utc', now())
  where id = active_row.id;

  next_number := active_row.season_number + 1;
  next_starts := timezone('utc', now());

  if extract(month from timezone('America/Los_Angeles', next_starts)) between 6 and 11 then
    next_ends := make_timestamptz(
      extract(year from timezone('America/Los_Angeles', next_starts))::integer,
      12,
      21,
      0,
      0,
      0,
      'America/Los_Angeles'
    );
  elsif extract(month from timezone('America/Los_Angeles', next_starts)) = 12 then
    next_ends := make_timestamptz(
      extract(year from timezone('America/Los_Angeles', next_starts))::integer + 1,
      6,
      21,
      0,
      0,
      0,
      'America/Los_Angeles'
    );
  else
    next_ends := make_timestamptz(
      extract(year from timezone('America/Los_Angeles', next_starts))::integer,
      6,
      21,
      0,
      0,
      0,
      'America/Los_Angeles'
    );
  end if;

  if next_ends <= next_starts then
    next_ends := next_starts + interval '1 day';
  end if;

  insert into public.basketball_seasons (
    season_number,
    display_name,
    starts_at,
    ends_at,
    is_active,
    schema_version
  )
  values (
    next_number,
    'Season ' || next_number::text,
    next_starts,
    next_ends,
    true,
    active_row.schema_version
  )
  returning id into active_row.id;

  return active_row.id;
end;
$$;

grant execute on function public.force_basketball_season_rollover() to anon, authenticated;
