create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.admin_settings (
  id boolean primary key default true,
  password_hash text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (id)
);

create table if not exists public.families (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  display_name text not null,
  family_id uuid references public.families (id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists players_display_name_unique_active
  on public.players (lower(display_name))
  where is_active = true;

create table if not exists public.game_types (
  id text primary key,
  display_name text not null,
  icon text not null default 'cards',
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.games (
  id uuid primary key default gen_random_uuid(),
  game_type_id text not null references public.game_types (id),
  display_name text not null,
  point_basis integer not null check (point_basis >= 1),
  money_per_point_cents integer not null check (money_per_point_cents >= 0),
  status text not null default 'open' check (status in ('open', 'settled')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  ended_at timestamptz
);

create table if not exists public.game_players (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games (id) on delete cascade,
  player_id bigint not null references public.players (id) on delete restrict,
  join_order integer not null check (join_order >= 1),
  is_locked boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (game_id, player_id),
  unique (game_id, join_order)
);

create table if not exists public.rounds (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null references public.games (id) on delete cascade,
  round_number integer not null check (round_number >= 1),
  game_type_id text not null references public.game_types (id),
  settings_snapshot jsonb not null default '{}'::jsonb,
  summary_text text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (game_id, round_number)
);

create table if not exists public.round_entries (
  id uuid primary key default gen_random_uuid(),
  round_id uuid not null references public.rounds (id) on delete cascade,
  game_id uuid not null references public.games (id) on delete cascade,
  game_player_id uuid not null references public.game_players (id) on delete restrict,
  player_id bigint not null references public.players (id) on delete restrict,
  point_delta integer not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  unique (round_id, game_player_id)
);

create table if not exists public.money_settlements (
  id uuid primary key default gen_random_uuid(),
  game_id uuid not null unique references public.games (id) on delete cascade,
  point_basis integer not null check (point_basis >= 1),
  money_per_point_cents integer not null check (money_per_point_cents >= 0),
  grouped_units jsonb not null default '[]'::jsonb,
  totals_snapshot jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.money_settlement_players (
  id uuid primary key default gen_random_uuid(),
  settlement_id uuid not null references public.money_settlements (id) on delete cascade,
  player_id bigint not null references public.players (id) on delete restrict,
  amount_cents integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (settlement_id, player_id)
);

create table if not exists public.money_transfers (
  id uuid primary key default gen_random_uuid(),
  settlement_id uuid not null references public.money_settlements (id) on delete cascade,
  from_player_id bigint references public.players (id) on delete restrict,
  to_player_id bigint references public.players (id) on delete restrict,
  family_label text,
  amount_cents integer not null check (amount_cents > 0),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_log (
  id uuid primary key default gen_random_uuid(),
  event_type text not null,
  entity_type text not null,
  entity_id text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create or replace view public.game_point_totals as
select
  gp.game_id,
  gp.player_id,
  gp.id as game_player_id,
  coalesce(sum(re.point_delta), 0) as point_total
from public.game_players gp
left join public.round_entries re
  on re.game_player_id = gp.id
group by gp.game_id, gp.player_id, gp.id;

create or replace view public.player_points_leaderboard as
select
  p.id as player_id,
  p.display_name,
  p.family_id,
  coalesce(sum(re.point_delta), 0) as total_points,
  count(*) filter (where re.point_delta > 0) as rounds_won,
  count(*) filter (where re.point_delta < 0) as rounds_lost
from public.players p
left join public.round_entries re
  on re.player_id = p.id
group by p.id, p.display_name, p.family_id;

create or replace view public.family_points_leaderboard as
select
  f.id as family_id,
  f.name as family_name,
  count(p.id) filter (where p.family_id = f.id and p.is_active) as member_count,
  coalesce(sum(re.point_delta), 0) as total_points,
  count(*) filter (where re.point_delta > 0) as rounds_won,
  count(*) filter (where re.point_delta < 0) as rounds_lost
from public.families f
left join public.players p
  on p.family_id = f.id
left join public.round_entries re
  on re.player_id = p.id
group by f.id, f.name;

create or replace view public.player_money_leaderboard as
select
  p.id as player_id,
  p.display_name,
  coalesce(sum(msp.amount_cents), 0) as total_money_cents
from public.players p
left join public.money_settlement_players msp
  on msp.player_id = p.id
group by p.id, p.display_name;

create or replace view public.game_summaries as
select
  g.id as game_id,
  g.display_name,
  g.game_type_id,
  g.status,
  g.created_at,
  g.updated_at,
  count(distinct r.id) as round_count,
  count(distinct gp.player_id) as player_count
from public.games g
left join public.rounds r
  on r.game_id = g.id
left join public.game_players gp
  on gp.game_id = g.id
group by g.id, g.display_name, g.game_type_id, g.status, g.created_at, g.updated_at;

create or replace function public.verify_admin_password(candidate text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  stored_hash text;
begin
  select password_hash
  into stored_hash
  from public.admin_settings
  where id = true;

  if stored_hash is null or candidate is null then
    return false;
  end if;

  return crypt(candidate, stored_hash) = stored_hash;
end;
$$;

grant execute on function public.verify_admin_password(text) to anon, authenticated;

insert into public.game_types (id, display_name, icon, sort_order)
values
  ('texas-holdem', 'Texas Hold''em', 'cards', 1),
  ('fight-the-landlord', 'Fight the Landlord (SE)', 'cards', 2)
on conflict (id) do update
set
  display_name = excluded.display_name,
  icon = excluded.icon,
  sort_order = excluded.sort_order;

create trigger set_admin_settings_updated_at
before update on public.admin_settings
for each row
execute function public.set_updated_at();

create trigger set_families_updated_at
before update on public.families
for each row
execute function public.set_updated_at();

create trigger set_players_updated_at
before update on public.players
for each row
execute function public.set_updated_at();

create trigger set_games_updated_at
before update on public.games
for each row
execute function public.set_updated_at();

create trigger set_game_players_updated_at
before update on public.game_players
for each row
execute function public.set_updated_at();

create trigger set_rounds_updated_at
before update on public.rounds
for each row
execute function public.set_updated_at();

alter table public.admin_settings enable row level security;
alter table public.families enable row level security;
alter table public.players enable row level security;
alter table public.game_types enable row level security;
alter table public.games enable row level security;
alter table public.game_players enable row level security;
alter table public.rounds enable row level security;
alter table public.round_entries enable row level security;
alter table public.money_settlements enable row level security;
alter table public.money_settlement_players enable row level security;
alter table public.money_transfers enable row level security;
alter table public.audit_log enable row level security;

create policy "public_read_families"
on public.families
for select
to anon, authenticated
using (true);

create policy "public_read_players"
on public.players
for select
to anon, authenticated
using (true);

create policy "public_read_game_types"
on public.game_types
for select
to anon, authenticated
using (true);

create policy "public_read_games"
on public.games
for select
to anon, authenticated
using (true);

create policy "public_read_game_players"
on public.game_players
for select
to anon, authenticated
using (true);

create policy "public_read_rounds"
on public.rounds
for select
to anon, authenticated
using (true);

create policy "public_read_round_entries"
on public.round_entries
for select
to anon, authenticated
using (true);

create policy "public_read_money_settlements"
on public.money_settlements
for select
to anon, authenticated
using (true);

create policy "public_read_money_settlement_players"
on public.money_settlement_players
for select
to anon, authenticated
using (true);

create policy "public_read_money_transfers"
on public.money_transfers
for select
to anon, authenticated
using (true);

create policy "public_read_audit_log"
on public.audit_log
for select
to authenticated
using (true);
